### ISSUE TITLE
First 15aa was trimmed

### ISSUE THREAD

**Issue by zyh4482** [idptools/finches#4]
When I tested different peptides, no matter how long the peptides are, I always get intermaps started from the 16th residue. The first 15aa of seq1 and seq2 are missing. Is it due to the window size? How could I obtain the full intermap?

**Comment by alexholehouse** [comment]
Hi @zyh4482 - firstly my apologies for the slow response here; I have been traveling extensively and am finally starting to catch up on things!

So, the intermaps use a sliding window (of size 30  (+1) by default), meaning the value at each intermap position encompasses contributions from a pair of regions that span from the index position +/- (windowsize/2).

What does this mean -  by default, with a window size of 30, position "16" (i.e. first position on intermap) is capturing residues 1 thru 31.

If you use a smaller window, then the first index gets closer to 1, but I would probably advise against going smaller than 10 or so because we've found the local smoothing of the chemistry ends up being pretty important to infer overall behavior! Happy to answer additional questions with slightly more expediency than this one :). Thanks!

**Comment by zyh4482** [comment]
Thank you very much for the clear response! 

> So, the intermaps use a sliding window (of size 30 (+1) by default), meaning the value at each intermap position encompasses contributions from a pair of regions that span from the index position +/- (windowsize/2).
> 
> What does this mean - by default, with a window size of 30, position "16" (i.e. first position on intermap) is capturing residues 1 thru 31.

If I understand correctly, the smoothed episilon of each position in intermap still represents the interaction potential of single residue, but it requires adjacent 15aa to work. That's why the first half of window size is dropped here. Am I right? 



In addition, I found a strange output. I used a different strategy to define IDR (including metapredict2). The IDR boundaries will be a little different from metapredict result. I used my sequence for generating heterotypic intermap as below. 

As shown in the figure, there is a strange "blank" between 40 - 90.
![CALVADOS](https://github.com/user-attachments/assets/240ee75b-48e8-49a9-9c73-2274d55cf02f)

But the matrix looks fine. 
[cf_intermap_data.csv](https://github.com/user-attachments/files/17141856/cf_intermap_data.csv)

The Mpipi model also produced the same result. 
![Mpipi](https://github.com/user-attachments/assets/4d81f4c6-deb1-4ee1-89d1-6a6bef5d53a3)

Mpipi matrix as below: 
[mf_intermap_data.csv](https://github.com/user-attachments/files/17141863/mf_intermap_data.csv)

Do you know what could be the reason?

**Comment by alexholehouse** [comment]
Ah yes - the blank is because these regions on the horizontal sequence are being defined as folded domains and the interactions between the those residues is being excluded (because we don't know which residues are surface accessible and which ones are buried). You can turn this off by setting `zero_folded` to `False`

**Comment by zyh4482** [comment]
Thank you very much!
